### ISSUE TITLE
Gateway accounts

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1388]
# Background

## Why?

We are going to introducing a range of features which requires the user to have a wallet, keys, funds and a membership, specifically

- Video NFTs
- Channel Social tokens
- Video Comments/Reactions

## `Atlas` today

In the current version of Atlas, this is not required, and there is in fact no notion of an account at all. There is certain user specific information which is persisted across sessions, using browser local storage, like search history, who you follow, etc., however it is not stored anywhere outside of local storage, and is not secured by any authentication.

## Gateways

Importantly, our goal is that near term onboarding of consumers into the Joystream ecosystem should not depend on them having wallet, keys, etc. , at least in order to enjoy the basic consumption features of the platform. The way we want to unlock this is through the Gateway system, described in this video

https://play.joystream.org/video/1266

Briefly, a gateway is an application on top of Joystream which plugs into the business model of the Joystream DAO by having to fund the access of it's users to the platform, and the application is free to monetise the end users however it desires to make this sustainable. Initially we expect everyone to fork and use `Atlas` for the experience in their gateway, but then we expect to see rapid iteration and experimentation using this reference. The `Atlas` product currently running on http://play.joystream.org, is not really a gateway, it's just a running instance of this product.

We currently do not have Gateways, but we are trying to build with it in mind, and once we have it, the information we currently store in local storage would almost certainly live on the infrastructure on which a given Gateway runs. Importantly, Gateways will almost certainly have user accounts of one kind or another, at least in order to limit how much free access the allow people to have through their product.

# Problem

The obvious challenge here is that `Atlas` is headed towards having two independent notions of an account with this setup

- the Gateway account: for simply accessing Joystream through the Gateway on which `Atlas` is being served.
- the Membership: the blockchain level representation of the user and their assets, comments, profile, etc.

How do we combine these in a rational way? How do we allow users to create, manage and select among these without getting confused?

# Proposal

One simple approach is to simply say that the two notions are totally orthogonal and separate.

- The memberships, which depends on there being a Polkadotjs extension, are the primary and visible profile, where it must be possible for the user to know which one they are using at any given time, and for all actions and information to be sensitive to this.
- The gateway account is a simple username & password sort of classical authentication scheme, which does not have a rich profile of any kind, is not visible by third parties on the Gateway or on Joystream in any way. The only purpose it serves is giving access to using `Atlas`, which under certain conditions may no longer be free for a given user host. Purely client side information, like who you follow, what you watched, what you searched for, would be local to each such gateway account, and be unaffected by what membership account you have selected.

This is one approach, there may be others.

# User Stories

- [ ]  Content viewer | have my search history saved across multiple devices.
- [ ]  Content viewer | save videos on private/public lists (playlists).
- [ ]  Content viewer | follow channels and get notified about new videos they publish.
- [ ]  Content viewer | like (or dislike) videos I watch. * (save saved videos on member profile)

**Comment by bedeho** [comment]
Covered by https://github.com/Joystream/atlas/issues/1820
