### ISSUE TITLE
NFT Issuing : Design

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1495]
### Info
"Issuing NFT" is a part of the NFT experience MVP scope.
This particular issue is a communication container for the whole "Issuing NFT" experience.

### User Stories in MVP scope:
- [ ] Video workspace - Issue a video as an nft while publishing it
- [ ] Video workspace - Issue a video as an nft while editing it
- [ ] Video workspace - Cancel an open auction
- [ ] My videos - Trigger issuing a video as an nft
- [ ] My videos - Trigger inspecting the nft in your profile (go to nft?)
- [ ] Issue NFT modal - Put video you created on auction
- [ ] Issue NFT modal - Put video you own on auction
- [ ] Issue NFT modal - Add royalties to open auction on nft panel
- [ ] Issue NFT modal - Cancel an open auction

**Comment by KubaMikolajczyk** [comment]
Video update 👇 🎥
NFT scope & Issuing NFT 
[https://www.loom.com/share/9c94d2aa78b549ecae4201cfc2e7f827](https://www.loom.com/share/9c94d2aa78b549ecae4201cfc2e7f827)

![Video workspace](https://user-images.githubusercontent.com/31144205/137583619-ee14e6e4-2bbc-43b1-8895-4787711acde7.png)

**Comment by KubaMikolajczyk** [comment]
Hello there!
New video update below 👇 
[https://www.loom.com/share/6733c26a239b4212a6a73097d1b90462](https://www.loom.com/share/6733c26a239b4212a6a73097d1b90462)

Link to figma: [Link to figma](https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=650%3A41176)

![Video workspace](https://user-images.githubusercontent.com/31144205/139469520-a915746f-7919-4cd4-ac23-e814555e8e60.png)

**Comment by dmtrjsg** [comment]
ℹ️  Latest Figma Designs : [Link> ](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=405%3A5330)

**Comment by KubaMikolajczyk** [comment]
Final video walkthrough: https://www.loom.com/share/9cc72ad4f658463baae2a6caa19b3255?sharedAppSource=team_library
