### ISSUE TITLE
NFT Notifications : Design

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1497]
### Info

"Notifications" is a part of the NFT experience MVP scope. This particular issue is a communication container for the whole "Notifications" experience design.

Child issues of this epic encapsulate design work.
Development is tracked in #1736 

### Features that must be included in MVP scope:

**Features**
- [ ] View notifications in drop down modal
- [ ] Get redirected to the action screen from notifications on click
- [ ] Mark all notifications as read
- [ ] View notifications in full screen notifications centre
- [ ] Mark selected notifications as read/ unread
- [ ] Mark all notifications as read/ unread

**Events**

- [ ] Notification center - Get notified when I earn a royalty from a transaction of an NFT I issued
- [ ] Notification center - Get notified when someone bids in an open auction of my NFT
- [ ] Notification center - Get notified when someone uses buy now in open auction of my NFT
- [ ] Notification center - Get notified when a bid in an open auction becomes withdrawable (by the person who placed a bid)
- [ ] Notification center - Get notified when someone withdraws their bid
- [ ] Notification center - Get notified when I win the auction (bid gets accepted)
- [ ] Notification center - Get notified if I get overbidded on an auction

**Comment by TCzechowski** [comment]
@bedeho two questions:

1. Do we want to display "tJOY account balance" and it's transaction history somewhere outside of notifications view? So the user is able to see how much royalties he earned, when, etc. (question related to the first notification from the list posted above)

2. What Joystream user can be notified about (in general, not only regarding the NFT)? Are notifications listed above the only things that the user can be notified about?

**Comment by bedeho** [comment]
1. Keep in mind that only issuers of NFTs, so channel owerns, can earn royalties, so if we wanted this kind of a notification, it would really be under the specific channel view on the studio side. I am not sure notifications is really the right model for this, perhaps it is, but there are a variety of revenue sources for a channel, so we may be better off just postponing this question of how to make it visible to a creator how much money they have earned to a later time. Is that ok do you think?
2. By user, I assume you mean a member as a consumer in Atlas, not a channel owner, or a curator, or a DAO participant of any kind. I think the other events will be related to Social Tokens, when they come, but also possibly participation in comment fields for example, where someone is replying to your comment, or reacting to you post. But I can't think of anything, at the moment for the stage we are at in the product now, that fits into notifications except the NFT stuff.

**Comment by kdembler** [comment]
@bedeho Are you positive all of those are technically feasible with the data we will be getting from the query node? I don't have a capacity at the moment to investigate unfortunately

**Comment by bedeho** [comment]
> Are you positive all of those are technically feasible with the data we will be getting from the query node? I don't have a capacity at the moment to investigate unfortunately

Not sure I understand what you are asking, but I am suggesting

- `we may be better off just postponing this question of how to make it visible to a creator how much money they have earned to a later time`
- `I can't think of anything... except the NFT stuff`

So I am not suggesting we do anything on the query node that is new, apart from basic NFT support, which @iorveth  is working on.

**Comment by kdembler** [comment]
I wasn't referring to your comment here, but the original issue content. I'm wondering whether we will be able to actually know when those events happen and be able to provide user with a notification. That would likely require access to some of the historical data/events around NFTs.

**Comment by bedeho** [comment]
Ok, yes we will just do the same thing we are doing for events in Pioneer, which is to explicitly index events as an entity implementing a global `interface` entity for events, so you can query across them.

**Comment by TCzechowski** [comment]
Hi @bedeho, new design update is here!

Update:
https://www.loom.com/share/00223f3e0119492284e097b3b2369b44

Figma file:
https://www.figma.com/file/0NTCE5yXyL4igxg6dPGz9m/Notifications?node-id=491%3A49307

Regarding quick actions that I've mentioned at the end of the video: Do you think there are more actions that require more advanced flow than just `confirmation dialog -> polkadot flow -> end.`? Maybe Accepting Bids is more complex than I thought? I assumed that these are going to be simplest processes possible, but maybe I don't know something.

Also, are those all notifications that the user can receive for now?
![image](https://user-images.githubusercontent.com/22870059/144428180-95bfcb05-59a7-4595-9ae4-76f8c05442a9.png)

**Comment by bedeho** [comment]
# Feedback

Thanks for an excellent and succinct video, this one was so easy to review.

- One very fundamental issue here is that technically executing on notifications requires some finess when we do everything client-side, so input from @kdembler will be pivotal in making sure we are picking a set of features that both are feasible, and do not require extreme time/tech cost to execute on. I will leave this evaluation for him.
- Overall I think it was an excellent approach. The main thing which I think could be difficult to execute on here is having actions on notifications. This is because, as I have mentioned on other reviews to @Lenorette , the state of an NFT or auction can change after the notification, which makes your this action on the original notification infeasible. As an example, lets say you receive a bid in an open auction, which would result a notification X, and X would have an action to `Accept bid`, but then later the bid is withdrawn by the bidder - because you spend too much time on it, now the `Accept bid` button has to no longer be visible on X. Now, this is technically possible to pull of, you would just have to be totally sure you have mapped all of these cases out properly. I think @kdembler can lend his view on how complex he thinks this will be for the team to pull off. I certainly see the value of the instant action for the user, at least for the most recent notifications.
- I did not see a full enumartion of all the notification types on Figma, it's all just generic placeholder stuff. https://www.figma.com/file/0NTCE5yXyL4igxg6dPGz9m/Notifications?node-id=445%3A27472 So I guess you will need to map those out properly, but I don't think I need to review those to be honest, it should be pretty straight forward.
- I am not sure I really understood the user goal the notifications deletion or marking as read is trying serve. I see that these features exist on FB for example, but in reality I have never actually tried to manage visibility or presence of notifications, its just an eternal stream of messages I look at to make sure I don't miss anything. I am happy to keep it, but to me it seems of very limited value, am I wrong?
- It seems like the drop-down is reserved for the generic actions that apply to _all_ notifications, and thus is it unlikely to really be anything besides delete or read. Given that we have so much horizontal space to play with here, could it improve the UX to simply put the two actions as top level actions on the notification itself, e.g. as lower contrast icon buttons or something, removing the need for a user to always have to expand the menu as an extra step to make the action? Not super important, but would like to hear your thoughts on this pattern.
- The notifications filtering seems like a very high powered feature that only extremely few people would use, so I would opt to drop it for now. While it does not harm the product much for non-users, it will help us simply restrict scope now and in the future, reducing execution time.

**Comment by kdembler** [comment]
Hey, sorry for the late reply, had to push this back slightly.

I see the concern you have around quick actions on notifications @bedeho and I kind of agree. It's really hard for me to tell how technically feasible those are at this point, I'm kind of guessing how the implementation would look like, until I have some visibility into the query node schema and what to expect from it. So depending on the query node this can be easy or hard to do. Maybe we say that quick actions are "nice to have" at this point and decide at a later point whether we should include them in the MVP?

**Comment by TCzechowski** [comment]
> Maybe we say that quick actions are "nice to have" at this point and decide at a later point whether we should include them in the MVP?

I'm okay with that, but I have to make sure the user will be able to perform all of the actions from another places. Need to speak with @Lenorette about that probably.

> As an NFT owner I want to be made aware when a bid in an open auction is about to become withdrawable

@bedeho I noticed the above user story in our spreadsheet and just want to confirm: Do we want to inform both the NFT owner and the buyer/collector or just one of them or maybe it’s just a typo in our document and we want to notify just the collector?

> As an NFT owner I want to get notified when someone buys using buy now in an open auction 
> As an NFT owner I want to get notified when someone buys using buy now in an English auction

Is there anything different about those two or both of those can use the same notification (e.g. **{username} bought your NFT for X tJOY**)?

**Comment by bedeho** [comment]
> I'm okay with that, but I have to make sure the user will be able to perform all of the actions from another places. Need to speak with @Lenorette about that probably.

Indeed, I have advocated for some sort of `overview` or  `home` view on the membership screen, where all available actionable NFTs are shown directly, but I don't think this was settled.

> I noticed the above user story in our spreadsheet and just want to confirm: Do we want to inform both the NFT owner and the buyer/collector or just one of them or maybe it’s just a typo in our document and we want to notify just the collector?

I guess the owner would want to be notified in advance, and the bidder perhaps after? I think it could work different ways, but this seems like a sensible starting point.

> Is there anything different about those two or both of those can use the same notification (e.g. {username} bought your NFT for X tJOY)?

Not really.

**Comment by Lenorette** [comment]
Yeah we indeed didn't settle on anything there, hoping that it could be somehow covered in Notifications.
I'll create new issue for this:
>Indeed, I have advocated for some sort of overview or home view on the membership screen, where all available actionable NFTs are shown directly, but I don't think this was settled.

**Comment by TCzechowski** [comment]
Final Loom walktrough:
https://www.loom.com/share/c01e648b42e2418aa0f67306996460f2

Figma file:
https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=0%3A1
