### ISSUE TITLE
Discovery milestone implementation feedback

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1508]
Couple of things we should fix:

- [x] No `Discovery` navigation item in sidenav
- [x] It's not possible to navigate via category cards
- [x] On category view, title of the section changes from `All videos ()` to `All videos(xxx)`. Let's improve the loading state and use just `All videos` when the number isn't available
- [x] The `Other filters` section is supposed to exclude selected items, not filter by them as it does currently
- [x] The loading state should be triggered when filters are changes to show the user something is happening. Currently there is no indication that new filters were applied

https://user-images.githubusercontent.com/12646744/138249368-e476668c-c234-4509-95d4-ad7792b9e1a5.mov

**Comment by kdembler** [comment]
- [x] There's no spacing between the last category card and the end of the page (vertically). The design specifies 64px there
- [x] The hover interaction with the category card can be broken by placing cursor on the edge of the card. Something like this has been fixed recently for VideoTiles by @drillprop, I suggest to reach out to him for quick fix

https://user-images.githubusercontent.com/12646744/140294205-e9cf2370-e6a8-47ba-8666-a30bdbafca1e.mov

- [x] Navigation via the category card doesn't work properly. It seems it's not handled by react router and navigation causes the full page to reload
- [x] Changing a filter causes the page to scroll down

https://user-images.githubusercontent.com/12646744/140294852-0d6d36cd-6035-4e41-9ec4-70799b141373.mov
