### ISSUE TITLE
NFT Improvements

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1625]
Scope tbd  based on progress with MVP

https://docs.google.com/spreadsheets/d/1AcS4mLXo8ybMwmBx93jwhpqtnEhn4nIVKokTOHtiAe4/edit#gid=0

# User Stories:

## Member Profile
- [x] #1805 
- [ ] #1804 - Done on mockups, needs to get connected.

## NFT Tile Actions

- [x] #1854 

## Direct Sale of NFT

- [ ]  NFT owner | offer the NFT to another member.
- [ ]  NFT owner | cancel an outstanding offer I have made to another member.
- [ ]  NFT owner | get notified when someone I offered an NFT to accepts.
- [ ] Collector | get notified when someone initiates an offer in my favour.
- [ ]  Collector | accept a pending offer in my favour.

## Misc
- [ ] Collector | stop getting notified about state changes in an NFT I previously was interested in
- [ ] Add support for NFT sling back
- [ ] Private Tracking of NFTs
- [ ] Bespoke DateTime Picker Component

**Comment by dmtrjsg** [comment]
'+ Scope: Ability of owners to bind messages to NFTs, and for these to be displayed in the player

**Comment by dmtrjsg** [comment]
+ Scope: Create Bespoke Calendar Component, issue #1794 added to Icebox pipeline
