### ISSUE TITLE
NFT Tile actions 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1802]
## Context

Dev epic for Tile Actions: User viewing NFTs on a member's profile tab and triggering various actions from the overflow contextual menu on the NFT tile.

## Designs

🎨  [Link to Figma > ](https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?node-id=972%3A218668)

## Scope

- [ ] Put NFT on sale from NFT tile
- [ ] Bid on NFT from NFT tile
- [ ] Edit NFT sale from NFT tile
- [ ] Cancel NFT sale from NFT tile

**Comment by dmtrjsg** [comment]
@kdembler 

Have we missed the English auction actions in this epic? Or is the naming confusing so should just be "auction" w/o specification of kind of auction?

Same with "Buy Now"?

**Comment by kdembler** [comment]
Yeah I think the naming on the issues is just confusing a bit. I think generic names would work better:
- Put NFT on sale from NFT tile
- Bid on NFT from NFT tile
- Edit NFT sale from NFT tile
- Cancel NFT sale from NFT tile
