### ISSUE TITLE
Reactions Dev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1876]
## Context
Dev epic for Reactions on video page.
🔧  Design epic: 
- #1985 

## Scope

- [ ] New way of handling transaction with minimised snack bar
- [ ] Component for likes/ dislikes + ratio in the bottom expressed as a bar (+ tooltip)
- [ ] Loading state for reactions
- [ ] Animation once its done
