### ISSUE TITLE
Playlists Dev Epic

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1877]
## Context

Dev Epic to encapsulate the design of Playlist feature.

Channel Owner - Creating and editing playlists
Content Viewer - Discovering and consuming playlists

## Design

Channel Owner - Creating & editing playlists

🔧  [Link to Design Epic> ](https://github.com/joystream/atlas/issues/2002)

Content Viewer - Discovering and consuming playlists
 🔧  [Link to Epic Detils >](https://github.com/joystream/atlas/issues/2002) 

## Additional Info

✏️  [Link to Detailed Brief ](https://github.com/Joystream/atlas/issues/1819)

#### Channel owner
[FIGMA Channel Owner > ](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=946%3A10510)

Create Playlist
- [ ] Playlist Details Page (create playlist)
- [ ] Playlist List Page (view my playlists with tabs and empty state)
- [ ] Add existing videos to playlist via search
- [ ] Publish playlist 
- [ ] Save as draft
- [ ] Create unlisted playlist
- [ ] Custom Thumbnail (NFT improvements candidate based on scope)

Edit playlist

- [ ] Edit playlist (+ delete last video)
- [ ] Update order of videos

Misc

- [ ] Copy Playlist link
- [ ] Play in Joystream
- [ ] Sort playlists in CO view

Transaction / Technical

- [ ] Handling transaction of playlist creation/ update/ delete [(Figma)](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=1052%3A31434)

#### Content viewer

[FIGMA Channel page >](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=899%3A58974)

[FIGMA Video page >](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1987%3A130699)

[FIGMA Playlist details page >](https://www.figma.com/file/f6pcaMR7bryFmszfrzTqJM/Playlist-details-page?node-id=927%3A50283) 

[FIGMA Search results page > ](https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=5%3A75378)

Components
- [x] Playlist tile
- [x] Playlist details
- [x] Playlist [Playing next]
- [x] Featured in [playlist]

Discovery of playlists (pages/ views)
- [x] Show playlists in All tab
- [x] Channel Playlists Tab
- [x] Sorting of playlists
- [x] Search results for playlists

Misc
- [x] Playlist video play in sequence/ order within PL
- [x]  Copy link to playlist
