### ISSUE TITLE
Creator Tokens Tracking

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1883]
#### Design Brief: Creator Social Tokens

The ability of creators to monetise their channel by sharing their future channel revenue with their most passionate fans, as well as give them access to unique content.

This video has some useful information on these topics
[https://play.joystream.org/video/275](https://play.joystream.org/video/275)

- [ ] https://github.com/Joystream/joystream/issues/2362
- [x] #1799 
- [ ]  #1813  

#### ⚠️ Outstanding Questions ⚠️ 
- [ ] QN Epics link https://github.com/Joystream/joystream/issues/3247
- [ ] Runtime Epics link TBD after brief is finishe
- [ ] Some [design concept was put together](https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=8980%3A234405), is this re-usable?
- [ ] Revenue share model scope tbd
- [ ] High level vision for relevant topics marked with ❓ 

#### Scope
**Publisher**
- [ ] Revenue Share with Community
> Equal allocation of  % total channel revenue ❓ 
- [ ] Community only board
>  Separate locked Community tab in comments section or smth more?; Community comments shown before regular❓ 
- [ ] Early Content Access
> timed release, optional or _"never"_ release to public view? (does the "never" make sense?) ❓ 

**Viewer**

- [ ] Revenue share - per model
> onboarding, dashboard with stats and notifications ❓ 
- [ ] Community Only Board
> As simple as Tab in the comments or what is meant by board? What can be community-only features ❓ 
- [ ] Early Content Access
> UI for restricted content, timed release to public views  ❓ 

**Out of scope**
- [ ] Parachains
- [ ] Full custody version
- [ ] Revenue share based on token holder activity (referrals, co-creation, content curation, chat responses moderation)

#### Designs 

Quick sketching for some ideas was done here  [Link to Figma> ](https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=8980%3A234405)

**Comment by dmtrjsg** [comment]
Outdated, superceded  by 
- https://github.com/Joystream/atlas/issues/2404
