### ISSUE TITLE
My videos - user flows / update designs 

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1933]
## Context

This issue encapsulates the changes layout of multiple pages in the studio view, driven by removal of multiple tabs functionality. 

# Dev

Scope of changes from previous version:

- [x] Remove multiple tabs support in content editor (publisher) flows
- [ ] The order of elements in dropdown of video tile context menu is changed
- [x] Dropdown itself is a different component then it was before in implementation (we now have a one that we use globally)
- [x] there is a destructive coloring for destructive actions inside of dropdown
- [ ] Different states of dropdown which depend on the state of video tile (nft/not nft etc.)
- [ ] Dialog for deleting video changed to a new one
- [ ] Snackbar added after copy video url chosen in dropdown

# Design

### Figma LInks

My videos file was updated and all tasks done:
- Designs: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=214%3A9736
- RWD: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=273%3A16015
- User stories: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=757%3A26710

### Todo tasks

- [x] Update all final designs 
- [x] Update all RWD screens
- [x] Prepare a list of user stories for this page
- [x] Create screen flows in figma for all user stories

Remove second tab from the screens covering the following use cases:

- As a publisher I want to upload a new video
- As a publisher I want to see my published video
- As a publisher I want to issue my existing video as an NFT
- As a publisher I want to edit an existing video
- As a publisher I want to edit an existing video for which there's an NFT issued previously

**Comment by KubaMikolajczyk** [comment]
My videos file was updated and all tasks done:
- Designs: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=214%3A9736
- RWD: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=273%3A16015
- User stories: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=757%3A26710
