### ISSUE TITLE
Playlist - Channel Owner: Design

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2002]
## Context

Design epic encapsulating the scope of Channel Owner wrt creating and managing Playlists

## Scope

Creating & editing playlists:
- [ ] As a channel owner, I want to create playlists by adding previously uploaded videos, setting up a name and a description, and a category (optional?), and specifying its visibility.
- [ ] As a channel owner, I want to edit previously created playlists.
- [ ] As a channel owner, I want to delete previously created playlists.

[FINAL FIGMA > ](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=946%3A10510)
[DEV EPIC](https://github.com/Joystream/atlas/issues/1877)

**Comment by dmtrjsg** [comment]
Base line scenario for Playlist thumbnails update:
1. Take from first video as dynamic link (updates with the video update)
2. Allow user to add a custom thumbnail to override point 1.

This will ensure we will never have empty thumb, plus some basic customisation supported :)

**Comment by KubaMikolajczyk** [comment]
@kdembler @dmtrjsg  
All of the work is done - final video update below 🤌 
https://www.loom.com/share/b8cba94a8c4e4274beb14a622242eebf?sharedAppSource=team_library
