### ISSUE TITLE
Subtitles - Viewing: Design

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2004]
## Context

Design epic covering Adding subtitles to published videos

## Scope

As a Content Viewer..

- [ ] Enable and disable subtitles/closed captions when watching a video.
- [ ] Choose a language of subtitles/closed captions when watching a video.
- [ ] My settings saved in local storage

Playback speed controls (Bonus):
- [x] #1503 
a. As a content viewer, I want to change the playback speed to be one of the predefined options.
b. As a content viewer, I want my playback speed preferences to be preserved when watching different videos.

## New Components

- [ ] Video Animation ⚠️ 

## Final Designs
Video walkthrough:
https://www.loom.com/share/cd7f7a5123e74f1fbf3f096fd32fb5e2

Figma designs:
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2119%3A135376

# DEV EPIC LINK
- #1875

**Comment by TCzechowski** [comment]
@dmtrjsg @bedeho @kdembler 

Video walkthrough:
https://www.loom.com/share/cd7f7a5123e74f1fbf3f096fd32fb5e2

Figma designs:
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2119%3A135376

**Comment by kdembler** [comment]
I've noticed that the `CC` animation appeared after you changed the subtitles language, even though they were already enabled. Is that desired or just Figma prototype thing?

Also not sure about this same animation for the playback speed change, does that bring much value to show it at all?

**Comment by toiletgranny** [comment]
@kdembler I'm not sure which animation you are referring to? 😅 
(cc @TCzechowski)

**Comment by TCzechowski** [comment]
@toiletgranny I think @kdembler meant the small, centered animation in 1:58 of my Loom video, @kdembler is that correct?

**Comment by kdembler** [comment]
Yes, exactly. Sorry, should have been more clear.

**Comment by toiletgranny** [comment]
Oh, ok, thanks @TCzechowski.

While the timing and the delay might actually deserve some tweaking (as it indeed looks rushed and perhaps even accidental) during implementation, the animation itself is very much intentional, with the reasoning behind it being: unlike YouTube, we recommend closing the settings menu right after making a choice, so that you — as a viewer — can focus on the content faster. The one tiny aspect we're giving away with this approach however is a visual confirmation of an action being registered. And so the center icon animation, with a label underneath, is displayed to compensate for that. I hope it makes sense!
