### ISSUE TITLE
Embedded player

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2215]
Atlas already supports MVP player that can be embedded on other sites and is already used in couple of places (Twitter playback, Joystream onoarding, http://droginfo.com.ua/content/view/10025/, etc.

Even though it works, I think we could make some improvements to make it work better:

- [ ] Make embedded player first-class experience - Make sure it works properly in embedded context, add some Joystream overlay, etc
- [ ] Fix some of the bugs associated with it
- [ ] Improve technical implementation - Decrease embedded bundle size, make the player more "isolated" from the rest of the app

**Comment by TCzechowski** [comment]
Figma link:
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2090%3A120662

1. Control bar: 
- added new component property (Embedded: True/False) + new variants (Embedded: True)
2. Player UI controls: 
- changed property name from Size to Type 
- added new property (Embedded: True/False) + new variants (Embedded: True)
4. Player UI: 
- changed property name from Size to Type
 - added new property (Embedded: True/False) + new variants (Embedded: True)
5. Video player:
 - changed property name from Size to Type
  - added new property (Embedded: True/False) + new variants (Embedded: True)
6. Added new variant for End Screen component
7. Added new “Top bar” component [LINK](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2583%3A232036)
8. Added new, “Small” variant to Play Button component [LINK](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2090%3A119950)

@kdembler is that documentation enough for you to document it in more detail? No new features here, we're using the same components but in different variants.
