### ISSUE TITLE
Comments Dev Epic

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2227]
Dev epic for https://github.com/joystream/atlas/issues/1986

- [x] Comments View Components [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140537)
+ Comments view for guest user [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2431%3A214814)
+ Comments Disabled [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411%3A219273)
- [x] Default view [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2431%3A214814)
- [x] Add comment to video [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140569) 
- [x] Edit my comment + cancel action [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140596)
- [x] View edit history of comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140609)
- [x] Reply to comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140576)
- [x] CO: Notification about posted comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2550%3A230287)
- [x] CV/CO: Sort Comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140537)
- [x] CO/CV reacts to comments link [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140555)
 - [x] CV: Delete Comment I left in the past[ link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140589)
- [x] CO: Delete comment viewers left in the past [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140616)
- [x] CV/CO: Notification about reply to my comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2544%3A228764)

**Comment by kdembler** [comment]
Done 🎉
