### ISSUE TITLE
Multiple Resolutions Support

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3317]
## Context

Multiple video playback resolutions is a feature that mature video streaming services have. This helps to ensure optimal experience for consuming video content across mobile and desktop where network connectivity may be lower.

## Scope

- [ ]  Multiple resolutions playback in Gleev
- [ ]  Multiple Resolutions in YPP auto-synch
- [ ] Multiple video resolutions added to QN metadata
- [ ] Multiple video resolutions supported in the storage and distribution nodes :warning: technical implementation tbc
