### ISSUE TITLE
Adaptive Streaming

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3318]
## Context

Adaptive streaming means automatically selecting the best video resolution, and switching to the optimium one, up or down a notch, depending on network connectivity and user agent.

## Scope
- [ ] Define the matrix for network connectivity and user
- [ ] Gleev Notification on switching the video resolution
- [ ] QN, same as multiple resolutions?
- [ ] Other infra impacted

Implementation tbd. [Useful link](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Setting_up_adaptive_streaming_media_sources)
