### ISSUE TITLE
Orion v2  atlas integration tracking issue 

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3630]
## Misc

- [x] fix typescript errors in cache.ts
- [x] bring back category view
- [x] bring back NFT history
- [x] fix unfollowing channel
- [x] fix /studio/channel form
- [x] fix useRawActivities 
- [x] fix filters bar
- [x] fix parseNotification in notification.hooks(?)

## Viewer

1. `Homepage` queries: 

- [x] Video hero(check if it's possible to change it and view it)
- [x] videos from followed channels
- [x] popular on atlas
- [x] new nfts on sale
- [x] Top 10 this week
- [x] Discover new channels(check what it means, and document this somewhere)
- [x] All content
- [x] Notifications
- [x] Search queries

2. `Popular` queries

- [x] Top 10 this month
- [x] Popular videos (check what "popular videos" means, and document this somewhere)
- [x] Popular channels (check what "popular channel" means, and document this somewhere)

3. `Nfts` queries
 
- [x] sorting works
- [x] filtering by date minted works
- [x] filtering by status works

4. `New & noteworthy` queries

- [x] Recently uploaded query
- [x] Promising new channels(check what "promising new channels" means, and document this somewhere)

6. Discover `queries`

- [x] Make sure we get the correct videos number for category.

7. Channels `queries`

- [x] top 10 channels
- [x] Discover new channels(check what it means, and document this somewhere)
- [x] Channels in your language

8. `Video` view queries

- [x] nft widget-related queries
- [x] video and video views
- [x] comments and comments reactions(check if it's possible to order them)
- [x] report the video mutation
- [x] reactions
- [x] more from the channel
- [x] more from category

9. `Channel` view queries

- [x] General channel query - make sure its possible to sort and search
- [x] make sure its possible to report channel
- [x] follows number
- [x] nfts collected by
- [x] NFTs tab, check if filters and ordering works as it should
- [x] Information tab - correct number of views and correct number of videos for a channel 

10. Category view queries

- [x] Featured content query, make sure it's possible to change video hero
- [x] videos query, make sure its possible to apply filters and change the order

11. `My profile/Edit profile` queries

- [x] NFTs owned(filters and ordering)
- [x] Activity
- [x] About

12. `Notifications` queries

- [x] make sure that we are getting all the notifications

## Studio

1. `My videos` queries 

- [x] sorting
- [x] tabs public and unlisted works

2. `Video workspace` 

- [x] correct data in video workspace

3. `My channel` queries

- [x] correct data on my channel form

**Comment by drillprop** [comment]
The basic integration with Orion v2 is basically done. There are some small things left, which I didn't manage to resolve. 

1. Few queries related to events have fetchPolicy set to `no-cache` as default. Queries work and we display correct data, but we can't use caching for them. The problem is, that for some unknown reason to me, apollo removes information about the NFT owner from the cache. Tried to fix this by editing the cache config, but no luck. This applies to queries:
 - useGetNotificationsQuery in `packages/atlas/src/api/hooks/notifications.ts`
 - useRawActivities in  `packages/atlas/src/api/hooks/notifications.ts`
 - useNftHistoryEntries in `packages/atlas/src/components/_nft/NftWidget/NftWidget.hooks.ts`

2.~In Orion v1. we used so-called custom queries. They are not supported in orion v.2 We need to figure out how we proper display them. This applies to:~ 
  - ~discoverChannels -  get list of 15 most followed channels out of 100 newest channels in random order~
  - ~promisingChannels - get list of 15 most watched channels out of 100 newest channels in random order~
  - ~popularChannels - get list of 15 most watched channels in random order~

~Small sidenote here - **popular videos** work as they should, i.e. works the same as in Orion v.1. We're taking the most viewed videos in a given period and we provide a `limit` that indicates on how many videos the connection should be capped.~

Edit: managed to shuffle results on the client. 

3. Batching is not working with the new Orion? We're getting the warning, that it's not supported. In Orion v1 we were using this mostly to batch three queries when someone enters the site: `'GetBasicVideos', 'GetDistributionBucketsWithBags', 'GetStorageBucketsWithBags'.` Not sure if it's actually needed now.
