### ISSUE TITLE
YPP programme Creator Emails

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3639]
@dmtrjsg commented on [Fri Jul 08 2022](https://github.com/Joystream/marketing/issues/263)

## Context

Implementation of Email notifications powered by Airtable status update

## Scope
- [ ] Triggers set up with Airtable status change
- [ ] "Your status is Approved" email copy and design
- [ ] "You have been paid for your content" email copy and design
- [ ] You are suspended

## Copy Input

TBD

**Out of scope ⛔ :**
May be possible to enhance this step via on chain event and Atlas notification (enhancement)
- [ ] Joystream/atlas#2985
- [ ] "Your status is not authorised" email copy and design

**Comment by dmtrjsg** [comment]
Will be covered in: 
- https://github.com/Joystream/atlas/issues/4084
- https://github.com/Joystream/orion/issues/126
