### ISSUE TITLE
Apps testing tracker

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3869]
## Operator
- [x] create a new appId
- [x] update an app
- [x] creating a channel
- [x] delete app (removed)

## Creator
- [x] upload a video inside an app
- [x] youtube-sync inside an app
