### ISSUE TITLE
Orion v2 Testing - Bugfixing Tracker

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3877]
## Context
- https://github.com/Joystream/atlas/issues/3821

~Instance for testing: https://atlas-caxlipfyi-joystream.vercel.app/~
Instance for testing on new playground: https://atlas-nuu0rufeu-joystream.vercel.app/

### Popular
1️⃣ 

- [x] 🟡  Popular on Atlas section shows 41 videos and the oldest is created 3 months ago. Videos are sorted by date created starting from newest.

**Videos**

2️⃣ 
- [x]  🟡 As a user, I should see a list of 50 the most viewed videos, sorted by date creation -> Shows 45 videos

**Channels**
- [x] 🟡 I should see only channels that have at least 4 videos

> https://atlas-2c7emdwly-joystream.vercel.app/channel/54?tab=Videos < this channel has 4 videos and not included into popular. Condition is set to strictly above 4, and not >=.

**NFTs**
3️⃣ 
- [ ] 🔴 As a user, I can filter NFTs using other filters, and the NFTs number is displayed correctly and I see correct results

This video is not included into promotional materials but is filtered out when "exclude promo: filter applied: https://atlas-2c7emdwly-joystream.vercel.app/video/134

**Channels**
4️⃣ 
- [x] 🔴 As a user, I see channels that have at least 1 video
[Example Channel> ](https://atlas-qq3f942az-joystream.vercel.app/channel/16?tab=Information)
Check "Malay"

⏯️  **To be retested on Prod**
- [ ]   a list of the 15 most watched channels out of 100 newest channels in random order

## Discover
5️⃣ 
- [ ]  🔴 As a user, I  see the correct number of videos of categories.
- [ ]  🔴  As a user, I see the categories chart displayed correctly(this one 👇)

**Category page**
6️⃣ 
- [ ] 🔴 As a user, I can change language and I see videos in this language, and the correct number of videos

**Video Page**
Comments

- [x] 🔴 As a user, I can sort comments by  most popular
Comment with no reactions and replies was filtered out. [See here> ](https://atlas-2c7emdwly-joystream.vercel.app/video/134)

**Search**
- [x] 🔴 Cannot search for "aliceChannel" - no search suggestions

### Mutations

7️⃣ to test on the new env

- [ ]  As a gateway operator, I can set category featured videos using setCategoryFeaturedVideos mutation
- [ ]  As a gateway operator, I can set supported categories using setSupportedCategories mutation

**Comment by drillprop** [comment]
1, 2 need to be fixed on Orion's side and the fix will be deployed probably on new playground.
I fixed 3 and 4. 
5,6,7 needs to be retested in the new playground with new categories(I'll add them myself in QN)

**Comment by drillprop** [comment]
I would say that 5 and 6 are also fixed.
