### ISSUE TITLE
Make all meta data for channels mandatory before creating channel (FE only)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3934]
## Context

To streamline channel creation for YPP programme participants we need to make all fields mandatory in the studio sign up flow

## Scope
- [ ] Add a line of text to the bottom of the step-helper element  (where 0/4 is) "All fields are mandatory".
⚠️ we could use the info panel markup or some other way to make it visible.. @KubaMikolajczyk to advise
- [ ] Remove ability to collapse the progress stepper on channel creation
- [ ] Always display cta "Add background image", rather than on hover
- [ ] When "add channel title" is clicked in the progress component move cursor to channel title edit (same mechanics as it now with description)

<img width="592" alt="Screenshot 2023-03-15 at 18 19 30" src="https://user-images.githubusercontent.com/93924525/225357841-335cc0d5-dfb6-43cc-a416-55bc64fa7208.png">

<img width="331" alt="Screenshot 2023-03-15 at 18 19 52" src="https://user-images.githubusercontent.com/93924525/225357849-d937b74b-7ea8-41ba-af57-1ad3222a9e1b.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204186378246509) by [Unito](https://www.unito.io)

**Comment by KubaMikolajczyk** [comment]
All design work is done and is covered in this user story ✅ 
(Saying exactly "All fields mandatory" in some label seems not to be needed with the new step approach that I proposed there - let me know wdyt)
https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?node-id=1405%3A21224&t=eOnvlMQaFwHxbyrT-4

**Comment by dmtrjsg** [comment]
Supeseded by:
- https://github.com/Joystream/atlas/issues/3938
