### ISSUE TITLE
Design Epic: Notification settings

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4084]
## Context

- https://github.com/Joystream/orion/issues/126
- #3639 

## Scope
- [ ] Notifications mgt for Member
- [ ] Notifications mgt for Channel
- [ ] Refreshed In-App notifications toasters
- [ ] Review if design change needed for Notifications page (in-app)
- [ ] Design html templates for Email Notifications

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @bedeho @attemka The refreshed in app notifications research & explorations is here where I walk you through some benchmarks, talk over the existing patterns and then show you my though process on iterations ✅ Its a bit longer but hopefully worth a watch :) https://www.loom.com/share/5d5b7d504f86467ab219d2838275c16c?sid=9f57cba2-fffa-4adf-969e-3591480caf3a

**Comment by dmtrjsg** [comment]
Great job @KubaMikolajczyk  ⭐ 

Pls see my comments: 

1. Figma and Dribble seem to be closest balance interms of social aspect of our platform use case.
2. Categorising is good: NFT, CRT, Engagement
3. Loving the design that is clean (preview of thumbs is an overkill and harder to implement)
4. Actions form overflow menu: Mark as read/unread.  I don’t think we need an option to `remove` and option to `turn off particular notiff`. 
5. Unread: Placing dot on the right makes your eyes go left to right when you are trying to skim.. so I actually like our present designs more with the highlight. If going with the dot let’s place it on the left?
6. Channel vs Member: should we only show based on whether user is in the studio/ viewer “mode”? Or perhaps merge them in a single view? In this case we need to think where we are taking the user when they click on notiff settings from the drop down. Suggestion is to remove the settings from the quick drop down and only add it to the notification centre page. The settings would then offer option to manage channel or member notiffs as two different links.
7. Lastly: I believe there are some notifications that are more important than the others (like accept bid/ increase bid/ settle auction) perhaps these actions can be surfaced to the notifications with a CTA embedded? I’m not strongly positioned for this but imho that would be nice.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg thank you for the feedback 🙌

3. Agreed!
4. Delete or hide action and a quick link to this particular setting for this notif - It's not something that is crucial but would be a great to give that options for the users. It ofcourse depends on how much time would have to be devoted to this part of task but I can see a big value in allowing user to customize their experience with notifications (where not customizable notifications can quickly become annoying for users). 
5. Why not :) we can try placing it on the left and making it smaller
6. OK i see the issue here. I agree that we have to offer two links instead of one - I overlooked that - but again if this is not just one place but two separate places where user can manage their notifs then giving them a quick option to go to a specific notif type setting from the single notif item would be a gigantic help for them to find the way to what they want to achieve quickly. Rather then asking them to find themselves where is the setting for being notified about liked video among two separate huge tables on two separate pages of settings :) not pushing, just making a point here
7. I'd love to explore this kind of action taking approach inside of notifications. I just didn't think that we wanted to devote more time on development of this - but with a green light I will go for it. However, I will need to construct a list of all notifications first before moving into notif actions design so we catch all of the most important ones and put them in the designs.

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk 
4. I have a strong feeling we should not invest in this in the first release. The notiff settings should be enough to manage these aspects, while deletion is def not required (what's there to hide? there isn't a use case of a like from an ex girfriend like on FB 😄 ).
5. Great, thanks for support on this one. 
6. I would also add a link to separate views but only from the full notification page view. I wasn't clear from your response which direction you wanted to take it forward but I am advocating to show both channel and member notiffs in the same drop down as missing notification has higher price than viewing an extra one. 
7. The list of notifications is [here>](https://github.com/Joystream/orion/issues/126) we only need actions on the NFT imho:

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg the Notifs work is still ongoing 🚧 but I managed to finish the whole notifications list for both channel & member and this work need a solid check - it was based on list here https://github.com/Joystream/orion/issues/126 - while looking throught the list and checking please keep in mind three things:

1. The video/ NFT title has to be at the very end of the sentence as the titles can get extremely long and we need to keep the core of the whole notification still visible so when checking the sentences and proposing changes please keep the video titles at the end.
2. Notifications by design are clickable UI elements so each notification has to link somewhere when clicking on it - please pay attention to proposed destinations I mention in "on click event" elements in tables. 
3. Sometimes there is a red "?" next to "on click event" - those are the notifications for which I have no initial idea about where should we link from them so I could use some ideas here 😭

📄 Link to channel notifications: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2471-75507&mode=design&t=Ig7rnXsTrdweotyp-4

📄 Link to member notifications: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2478-89758&mode=design&t=Ig7rnXsTrdweotyp-4

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @attemka @bedeho this is a bigger part of the final update - still a few minor design items are needed to close this Epic but overall the huge majority of work is here and ready to be reviewed - the whole notifications rework ✅

🎥 Loom video: https://www.loom.com/share/05a6016769734807aea4374cc928f177?sid=6b375acc-66fa-4875-a958-b95e5d84e20b

📄 Link to notifications changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=1111-55611&mode=design&t=O8RJ8xxL5ZW21QVd-4

📄 Link to my channel changelog: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=703-5383&mode=design&t=NW7h0JDNkP4EtGWC-4

📄 Link to membership profile changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2912-46498&mode=design&t=aaTWo3DsN4XDB0Ce-4

**Comment by dmtrjsg** [comment]
Excellent work ⭐ 
The only thing I would suggest to consider is a shortcut link between member and channel notifications (from the notifications center and drop down overflow menus perhaps?) 
Also if we could just have a counter of new notifications for  this option, that way we ensure that no notiffs are missed and user can review all new notifications in the "connected" journey..

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @attemka @bedeho  the last update finishing all design work on notifications is ready to be reviewed ✅ 

All of the topics are covered in this update - you can find all of those elements by inspecting the changelogs of files mentioned below 👇
1. All new and updated notification events added to membership profile notification settings (based on notification events)
2. All new and updated notification events added to my channel notification settings (based on notification events)
3. All notification events are updated based on feedback
4. Added mobile variants of notification widget list item and notification tile (and described everything in the documentation)
5. Added email notifications templates + desired behavior documentation

📄 Notifications changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=1111-55611&mode=design&t=L5bUQ1XDHV9505ZJ-4

📄 Member profile changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2912-46498&mode=design&t=2XKM1HpaWnJmDb0x-4

📄 My channel changelog: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=703-5383&mode=design&t=UxMrqmqr5U5ZT40a-4

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @attemka I added the user story about switching from one notification center to another & badge notification to avatar in top nav component along with extensive documentation about its desired behavior

📄 Notifications changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=1111-55611&mode=design&t=UVwPaCRw84NUv6JY-4

📄 Top navigation changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9151-168457&mode=design&t=reJZigq5B8tPc9e9-4

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg I edited the email template to contain all member & channel notifications in one bundled email ✅

📄 Notifications changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2793-31278&mode=design&t=0XVW550aqoDG3U22-4
