### ISSUE TITLE
Glue all user accounts components

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#4263]
## Todo

- [ ] Add triggers for the login modal in the correct place
- [ ] Integrate new handlers from auth provider to login
- [ ] Verify whether basic flows work as expected (signup, login with email, login with wallet)
- [ ] Integrate protected action with auth provider
- [ ] Verify session persistence on re-entry
- [ ] Nice to have - introduce AuthenticationModalStepTemplate for every auth modal
