### ISSUE TITLE
CRT DAO QA #5360

### ISSUE THREAD

**Issue by polikosi** [Joystream/atlas#5483]
- [x] Placeholder screen:
Token placeholder screen #3396
https://github.com/Joystream/atlas/issues/3396#issuecomment-1824525436
[Designs>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=5-13358&mode=design&t=8wP4RIvrq3Gs1FhO-0)

 - [x] Create CRT flow:
Component: split ratio slider #3401
https://github.com/Joystream/atlas/issues/3401#issuecomment-1824486175
[Designs>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=8%3A34229&mode=design&t=XlaxUQAhKPbhpx8K-1)
Comment: Chart is better than token preview because it reacts to initial price.

- [x] Create CRT Flow #3385
https://github.com/Joystream/atlas/issues/3385#issuecomment-1824571756

- [x] Submit token extrinsic #3394
https://github.com/Joystream/atlas/issues/3394#issuecomment-1824590149
Comment: Due to technical implementation constraints decided to keep as-is.

- [x] Vesting schedule chart POC #3402
https://github.com/Joystream/atlas/issues/3402#issuecomment-1819573675

- [x] Create CRT Flow Previews #3386
https://github.com/Joystream/atlas/issues/3386#issuecomment-1824583511
Comment: Tooltips will be handled in a separate issue; Lock icon not possible to add; Dot on the chart will be added.

- [x] Create CRT Flow Custom Params #3387
https://github.com/Joystream/atlas/issues/3387#issuecomment-1824584454
Comment: Decided to add validation on the input

Dashboard:
- [x] CRT Dashboard Structure #3388
I need to retest it tomorrow.
https://github.com/Joystream/atlas/issues/3388#issuecomment-1824675461

upd: https://github.com/Joystream/atlas/issues/3388#issuecomment-1825500156

- [x] CRT Dash Progress Widget #3389
https://github.com/Joystream/atlas/issues/3389#issuecomment-1824753163

- [x] CRT Dash "Core" Token Widgets #3390
https://github.com/Joystream/atlas/issues/3390#issuecomment-1824702927

UPD 24.11 below:
Token Page:
- [x] CRT Token Page Structure #3391
https://github.com/Joystream/atlas/issues/3391#issuecomment-1825935044

- [x] Markdown Editor POC #3403
https://github.com/Joystream/atlas/issues/3403#issuecomment-1825949897

- [x] CRT Token Page Select video trailer #3392
https://github.com/Joystream/atlas/issues/3392#issuecomment-1825960889

- [x] CRT Token Page Benefits #3393
https://github.com/Joystream/atlas/issues/3393#issuecomment-1825985857

Token Market:
- [x] Token Start Market Flow UI #3797
https://github.com/Joystream/atlas/issues/3797#issuecomment-1825545913

- [x] Token Start Market flow Chart #3798
https://github.com/Joystream/atlas/issues/3798#issuecomment-1825553715

- [x] Token Market: Submit Tx #3799
https://github.com/Joystream/atlas/issues/3799#issuecomment-1825558474

- [x] Token Market Tab #3802
https://github.com/Joystream/atlas/issues/3802#issuecomment-1825578563

- [x] Token Market: Dashboard Widget #3805
https://github.com/Joystream/atlas/issues/3805

upd 01.12
### Holder
- [x] Creator: Views Token Holders in Tab #3841
https://github.com/Joystream/atlas/issues/3841#issuecomment-1835832091

- [x] CRT Viewer: Buy Tokens on Market - Submit tx #3835
https://github.com/Joystream/atlas/issues/3835#issuecomment-1835740159

- [x] Creator: Token Holders Widget on Dash #3842
https://github.com/Joystream/atlas/issues/3842#issuecomment-1835854194

- [x] Holder: Token Portfolio #3856
https://github.com/Joystream/atlas/issues/3856#issuecomment-1836063067

- [x] Holder Portfolio: Buy from Sale/ Sell and Buy from AMM #3859
https://github.com/Joystream/atlas/issues/3859#issuecomment-1836090857

upd 06.12
### Revenue Share
- [x] Creator: Revenue Share Tab #3844
https://github.com/Joystream/atlas/issues/3844#issuecomment-1839282051

- [x] Creator: Start Revenue Share #3845
https://github.com/Joystream/atlas/issues/3845#issuecomment-1840805978

- [x] Creator: Start Rev share submit tx #3846
https://github.com/Joystream/atlas/issues/3846#issuecomment-1840853428

- [x] Creator: Revenue Share progress widget #3847
https://github.com/Joystream/atlas/issues/3847#issuecomment-1841599038

- [x] Creator: Revenue Share history widget #3848
https://github.com/Joystream/atlas/issues/3848#issuecomment-1843121483

- [x] Creator: Staked Holders for Rev Share #3849
https://github.com/Joystream/atlas/issues/3849#issuecomment-1843178020

- [x] Creator: Close completed Revenue Share #3850
https://github.com/Joystream/atlas/issues/3850#issuecomment-1843204938

- [x] Creator: Revenue Share Dash Widget #3851
https://github.com/Joystream/atlas/issues/3851#issuecomment-1841572688

- [x] CRT Viewer: Revenue Share Widget #3852
https://github.com/Joystream/atlas/issues/3852#issuecomment-1843289179

upd 07.12
- [x] Holder Portfolio: Revenue Share widget #3862
https://github.com/Joystream/atlas/issues/3862#issuecomment-1845736747

- [x] Holder Portfolio: Stake Tokens for Revenue share #3863
https://github.com/Joystream/atlas/issues/3863#issuecomment-1845877503

Bugs:
@dmtrjsg check it please. Perhaps some of them are out of scope
#5479 🟢 
#5480 🟢 
#5481 🟢 
#5482 🟢 

24.11 new bug
https://github.com/Joystream/atlas/issues/5493 🟢 

06.12 new bugs:
https://github.com/Joystream/atlas/issues/5586
https://github.com/Joystream/atlas/issues/5589
https://github.com/Joystream/atlas/issues/5590
https://github.com/Joystream/atlas/issues/5598
https://github.com/Joystream/atlas/issues/5599
https://github.com/Joystream/atlas/issues/5600

07.12 
https://github.com/Joystream/atlas/issues/5609
https://github.com/Joystream/atlas/issues/5610

**Comment by dmtrjsg** [comment]
Additionally:

- https://github.com/Joystream/atlas/issues/3825#issuecomment-1836604704
- https://github.com/Joystream/atlas/issues/5572

**Comment by WRadoslaw** [comment]
Closed in favor of https://github.com/Joystream/atlas/issues/5636
