### ISSUE TITLE
CRT DAO QA v2

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#5636]
### Revenue share

- [x] Add case when holder recovers staked tokens - hide the action button

---

### Revenue share

- [x] Remove input from start revenue share modal https://github.com/Joystream/atlas/issues/3845#issuecomment-1840805978
- [x] Fix link to the token tab for channel https://github.com/Joystream/atlas/issues/5599
- [x] Revenue share actions on different channels https://github.com/Joystream/atlas/issues/5598
- [x] Check why there is no "starts in" state in revenue share https://github.com/Joystream/atlas/issues/5609
- [x] Check why the token is displayed as ongoing although it's upcoming https://github.com/Joystream/atlas/issues/5610

### Portfolio 

- [x] Add expandable revenue shares to portfolio https://github.com/Joystream/atlas/issues/3862#issuecomment-1845736747

---

### Orion

- [ ] Add historical potential revenue share participants https://github.com/Joystream/atlas/issues/3848#issuecomment-1843121483

### Animations

- [ ] CRT Dash Progress Widget CRT Dash Progress Widget https://github.com/Joystream/atlas/issues/3389#issuecomment-1828002918

---

Previous issue https://github.com/Joystream/atlas/issues/5483

**Comment by polikosi** [comment]
### **Create CRT flow:**

- [x] Сhart above 100% https://github.com/Joystream/atlas/issues/3385#issuecomment-1852296381

- [ ] Make only numbers and commas/dots available https://github.com/Joystream/atlas/issues/3387#issuecomment-1852317314

### **Dashboard:**
- [x] Add text "No holders yet" below the "top holders" icons https://github.com/Joystream/atlas/issues/3388#issuecomment-1852385681

- [x] https://github.com/Joystream/atlas/issues/3390#issuecomment-1852414293

### **Token Market:**

- [x] Confirmation message that the market has started https://github.com/Joystream/atlas/issues/3802#issuecomment-1852504834

- [x] Change "Show sales" to "Show market" https://github.com/Joystream/atlas/issues/3805#issuecomment-1852485903

**Comment by polikosi** [comment]
bug: https://github.com/Joystream/atlas/issues/5650
### **Token Market:**

- [x] Wrong token name and I can close the market https://github.com/Joystream/atlas/issues/3804#issuecomment-1854479021
Edit: This issue is to be resolved by https://github.com/Joystream/atlas/issues/5391

**Comment by ivanturlakov** [comment]
Retested on https://atlas-7id1hwe0w-joystream.vercel.app

### Viewer
- [x] Token Page > Description - add/delete benefits feature [issue](https://github.com/Joystream/atlas/issues/3825#issuecomment-1836604704)

- [x] Token Page > Header Widget - short description & invite-only label display [issue](https://github.com/Joystream/atlas/issues/3826#issuecomment-1842978601)

- [ ] Token Page > Holders Table - Hover view all tokens - looks like not been implemented yet

**Comment by polikosi** [comment]
### **Holder:**
- [x] Snackbar and sorting by the amount of tokens https://github.com/Joystream/atlas/issues/3835#issuecomment-1856130049 / Partially done, needs response

- [x] Percentage of tokens held by the owners and pie chart https://github.com/Joystream/atlas/issues/3842#issuecomment-1856152850

- [ ] The wrong page opens https://github.com/Joystream/atlas/issues/3856#issuecomment-1856177366

- [x] Does not match the design a bit. Add pagination. https://github.com/Joystream/atlas/issues/3841#issuecomment-1856251454

- [x] Add "Sell" button on portfolio page https://github.com/Joystream/atlas/issues/3859#issuecomment-1856290971

**Comment by polikosi** [comment]
### **Revenue share:**

- [x] when the revenue share is active, it should be "Holders staked" and the number of participants https://github.com/Joystream/atlas/issues/3847#issuecomment-1863398693

- [x] Wrong calculation of the total and holders claimed tokens https://github.com/Joystream/atlas/issues/3848#issuecomment-1863408665

- [x] Add name of table https://github.com/Joystream/atlas/issues/3849#issuecomment-1863415967

- [x] Add the sign plus https://github.com/Joystream/atlas/issues/3851#issuecomment-1863429087

- [x] Notification, add link, change timer to relative date and time https://github.com/Joystream/atlas/issues/3852#issuecomment-1863543946
EDIT: Notifications are out of this QA scope

**Comment by ivanturlakov** [comment]
### Revenue share:

YOUR_SHARE & YOUR_TOKENS values before claiming looks incorrect https://github.com/Joystream/atlas/issues/3864#issuecomment-1866429388

Locked tokens display in table(lock icon missed/alignment) https://github.com/Joystream/atlas/issues/3863#issuecomment-1866549366

**Comment by ivanturlakov** [comment]
### Unchecked(still actual)

- [x] **Snackbar missed** https://github.com/Joystream/atlas/issues/3835#issuecomment-1917580121
- [x] **Add link "See in portfolio in each stages"** https://github.com/Joystream/atlas/issues/3852#issuecomment-1863543946

Both by https://github.com/Joystream/atlas/pull/5860

✅ Tested on Preview - atlas https://atlas-ljl8f2n3r-joystream.vercel.app 08.02 👍

**Comment by ivanturlakov** [comment]
### Claim/Unlock

**Before Claim** - Can we Calculate _Your Share & You Will Receive_ (Portfolio & Claim Modal)?

<img width="492" alt="Screenshot 2024-02-08 at 11 44 24" src="https://github.com/Joystream/atlas/assets/46903215/7e122155-47c6-4801-bef7-12467144a174">
<img width="1320" alt="Screenshot 2024-02-08 at 11 40 25" src="https://github.com/Joystream/atlas/assets/46903215/416c5fca-0ff6-42e0-b12d-1867678e0c5c">


**After Claim** - Calculate _Your Tokens_ value + add Lock Icon

<img width="1313" alt="Screenshot 2024-02-08 at 16 10 04" src="https://github.com/Joystream/atlas/assets/46903215/8081cf07-0765-4347-9330-ca7426b41b0e">

<img width="1322" alt="Screenshot 2024-02-08 at 16 13 47" src="https://github.com/Joystream/atlas/assets/46903215/0d984ddc-befd-408d-9453-31e7f4cb3e73">

Design

<img width="1065" alt="Screenshot 2024-02-08 at 11 46 02" src="https://github.com/Joystream/atlas/assets/46903215/3be566e3-048e-4957-8614-73efdb531dd6">


### Edit Token Page
- No chance to delete all benefits
- Short description duplicates About section

### ⚠️ Portfolio > Sell Token Modal
- When attempting to sell multiple tokens sequentially, the modal window displays _Available balance_ of the token that was sold first

### Token Dashboard, Token Revenue Share
- Change “Ended On” to “Holders Staked” for all stages
<img width="626" alt="Screenshot 2024-02-08 at 15 51 41" src="https://github.com/Joystream/atlas/assets/46903215/5215fcb0-2a66-4189-818b-73a188456fdc">
<img width="1253" alt="Screenshot 2024-02-08 at 15 49 21" src="https://github.com/Joystream/atlas/assets/46903215/f1d00416-888c-4a4b-8be2-0dc42287268a">

**Comment by WRadoslaw** [comment]
> ### Token Dashboard, Token Revenue Share
> * Change “Ended On” to “Holders Staked” for all stages

It's in line with the designs, so no changes. "x% holders" indicate what it means exactly

**Comment by WRadoslaw** [comment]
> * Short description duplicates About section

It's metadata issue, we don't have a way to set short description.

> * No chance to delete all benefits

It needs to be done on the Orion side (or is already done)

> **Before Claim** - Can we Calculate _Your Share & You Will Receive_ (Portfolio & Claim Modal)?

The expected payout is calculated on Orion and it is returning 0 all the time, so it needs to be fixed there.

**Comment by kdembler** [comment]
I did a bit of testing myself and found some issues. Apologies if some have been reported already!

### Creating a token

- [ ] "Learn more" doesn't link anywhere
![CleanShot 2024-02-13 at 14 19 55@2x](https://github.com/Joystream/atlas/assets/12646744/5f7c24fa-b7c5-437d-b4d4-ef9c1904090b)

- [ ] Confusing revenue share tooltip. It seems the second part is about annual rewards, not revenue share, and contains some placeholders.
![CleanShot 2024-02-13 at 14 24 59@2x](https://github.com/Joystream/atlas/assets/12646744/b425f0b4-0666-419b-b5da-a9f8b153caf0)

- [ ] "Learn more" in this banner doesn't link anywhere
![CleanShot 2024-02-13 at 14 26 11@2x](https://github.com/Joystream/atlas/assets/12646744/5965c9eb-6625-4de7-9005-d4469ec335ec)

### Token dashboard

- [x] "Total revenue" shows some amount of tokens, even though this is a new channel and has not earned anything yet.
![CleanShot 2024-02-13 at 14 28 19@2x](https://github.com/Joystream/atlas/assets/12646744/41a83d94-2f8a-4030-9426-88327d598b2c)

### Starting a market

- [x] "Sale" button is not available. If it's "coming later" feature, we should show something that describes it, currently it feels broken.
![CleanShot 2024-02-13 at 14 29 08@2x](https://github.com/Joystream/atlas/assets/12646744/5e80c92a-1f94-4c01-a91f-2338ffc0c9ab)

- [ ] Both "Learn more" don't link anywhere (screenshot above)
- [ ] Terms and conditions default value contains lorem ipsum placeholder
![CleanShot 2024-02-13 at 14 31 03@2x](https://github.com/Joystream/atlas/assets/12646744/7ec73c53-d748-4733-a924-02421d5d9bd4)

- [x] After submitting the transaction, a modal with instructions appears but disappears immediately.

https://github.com/Joystream/atlas/assets/12646744/ae414ffa-36e8-4326-96b0-720b1a7b0537

### Market

- [x] Atlas "lets me" buy 1.5 tokens, even though the CRTs amounts are represented as integers. Concept of half a CRT doesn't exist
![CleanShot 2024-02-13 at 15 04 25@2x](https://github.com/Joystream/atlas/assets/12646744/96c64a90-1e5e-49a4-9e80-507615cea8f5)
- [ ] Terms when buying a token are a lorem ipsum placeholder
![CleanShot 2024-02-13 at 16 07 28@2x](https://github.com/Joystream/atlas/assets/12646744/329a2383-8d3a-4134-934a-d66dd1353991)

- [x] Close market modal is showing incorrect data. It claims I need to sell _-10 tokens_. Apart from the fact that it wants me to sell a negative amount, I have just opened a market and have not made any transactions on it, so I own all of the supply and should be able to close without issues.
![CleanShot 2024-02-13 at 15 05 44@2x](https://github.com/Joystream/atlas/assets/12646744/c534abb3-221c-4c89-869b-f2ccf8a8e555)

- [x] State of buy modal is not reset after I make a purchase. When I want to buy a second time I'm taken directly to the summary

https://github.com/Joystream/atlas/assets/12646744/b63f2b71-3325-4dd5-a581-4d08ada4c19f


- [ ] The status of the market is not really explained anywhere. If I have 100 tokens but AMM can buy back only 10 tokens, the UI properly sets 10 when I click 100%, but it's not explained. This will be confusing to users.
- [x] The buy price estimation is incorrect in some cases. I have bought and sold 10 tokens, leaving the total supply at the initial value. However, when I try to buy 10 tokens again, the estimate cost is much higher than for first 10 tokens that I bought. UI shows 8.6K JOY, when I actually paid only 1.5K JOY:
![CleanShot 2024-02-13 at 15 45 29@2x](https://github.com/Joystream/atlas/assets/12646744/0dbbd31e-4074-42af-b81a-0b6d1be0e48e)
![CleanShot 2024-02-13 at 15 47 45@2x](https://github.com/Joystream/atlas/assets/12646744/f7c31714-d207-480b-8a42-b876defbc11e)
- [ ] I have created 2 separate tokens with exact params and then started AMM for both of them with the same params. That however has resulted in slightly different AMM settings. Shouldn't that be deterministic? 
![CleanShot 2024-02-13 at 15 54 49@2x](https://github.com/Joystream/atlas/assets/12646744/1afe455c-d59d-4484-a5ba-e78dd581c9f1)

### AMM pricing

- [ ] I find token pricing for AMM confusing. In the UI I have set the "Starting price for token" at 1 JOY. However, the graph shows that first token would cost ~38 JOY.
![CleanShot 2024-02-13 at 14 31 19@2x](https://github.com/Joystream/atlas/assets/12646744/6845fd6e-72d6-4193-807a-1a15117e79a3)
In the same spirit, the graph claims that at 1k supply of my token (initial supply in my case), the price would be 24.6K JOY.
![CleanShot 2024-02-13 at 14 31 13@2x](https://github.com/Joystream/atlas/assets/12646744/3c071b29-5242-4b4a-b46e-7d2a6c2a5abd)
Then, when market is actually started, even though the token is at 1k supply, one unit costs 36.3 JOY which doesn't match any of the previous estimates.
![CleanShot 2024-02-13 at 14 58 32@2x](https://github.com/Joystream/atlas/assets/12646744/356a2882-6a06-4c9c-ac4b-4beadad01df6)

### Misc 
- [ ] I'm seeing some console errors:
![CleanShot 2024-02-13 at 15 12 12@2x](https://github.com/Joystream/atlas/assets/12646744/75031a1b-c9d1-4909-8f8b-f90ecf946353)
![CleanShot 2024-02-13 at 15 12 21@2x](https://github.com/Joystream/atlas/assets/12646744/2f77d743-a77e-4e5a-b33c-917ca58aae67)

**Comment by WRadoslaw** [comment]
> * I have created 2 separate tokens with exact params and then started AMM for both of them with the same params. That however has resulted in slightly different AMM settings. Shouldn't that be deterministic?

It uses live JOY fiat price to determine this if I remember correctly.



> * I find token pricing for AMM confusing. In the UI I have set the "Starting price for token" at 1 JOY. However, the graph shows that first token would cost ~38 JOY.

Can't help you with that, I was doing this whole thing with @ignazio-bovo guidance `packages/atlas/src/utils/crts.ts:3` is the function that is used to calc the value inside `packages/atlas/src/components/_crt/MarketDrawer/MarketDrawerPreview.tsx:32`

**Comment by kdembler** [comment]
> It uses live JOY fiat price to determine this if I remember correctly.

Why would that be the case? During the AMM activation flow, the user is asked to provide the initial price, so what would we use fiat for?

**Comment by kdembler** [comment]
- [ ] I "have" $17M just by minting a new token (this is Studio token view, also portfolio)
![CleanShot 2024-03-04 at 11 44 52@2x](https://github.com/Joystream/atlas/assets/12646744/47133dee-bd3e-4ff3-ba3f-dfe1a8a56a74)

**Comment by dmtrjsg** [comment]
Tried to start revenue share with a newly created channel, after having created tokens + minted more on AMM.

I wasn't able to:

1. 🔴 From Dashboard widget the button was not active at all   -> needs to mimic the exact behaviour of button in the Revenue share tab, so clickable and summoning the dialogue, with the same validation error as in the point below
2. 🟡  From Revenue share tab after attempt to start it, got message: 

`Cannot start revenue share
There are no assets on the channel that could be shared with holders.`

Which was confusing to me as creator. 

<img width="831" alt="Screenshot 2024-03-04 at 16 06 26" src="https://github.com/Joystream/atlas/assets/93924525/7e7ed4eb-cd3d-4faf-b8b7-48e3a52ca9ce">


⚠️ Suggestion: reword to 
- [x] `There are no assets on the channel that could be shared with holders.` -> `Your channel reward account must have positive JOY balance. YPP, NFT sales and DAO rewards result in channel rewards." @WRadoslaw

**Comment by dmtrjsg** [comment]
Two more cases: 

- [x] 1. Tooltip on Revenue share on teh token page has reverse ratio of revenue share: 
<img width="718" alt="Screenshot 2024-03-05 at 14 16 55" src="https://github.com/Joystream/atlas/assets/93924525/c0adb499-a4b3-4e1a-a9af-dc837d4f18b0">

<img width="296" alt="Screenshot 2024-03-05 at 14 18 18" src="https://github.com/Joystream/atlas/assets/93924525/126204ff-8d94-4cde-bf84-613c7f3a03b8">

⚠️ So in the tooltip it must say Holders 20, Channel 80


- [ ] 2. When creator sets up starting price for CRT in JOY (e.g. 1  joy). The first buyer of the token must pay exact price that creator set up. 

In the screenshot below one can see that price in JOY is a LOT higher (for the example of 1 JOY the first buyer sees 236 JOY for purchase of one token)

<img width="438" alt="Screenshot 2024-03-05 at 14 21 35" src="https://github.com/Joystream/atlas/assets/93924525/6d04ad8f-efe6-4cc3-b8f0-dcf3a2645a20">

**Comment by dmtrjsg** [comment]
Full list of learn more links that need to be removed is here:
- https://github.com/Joystream/gleev/issues/30

**Comment by dmtrjsg** [comment]
##  Token UX and UI

1️⃣  Suggesting to update the token ticker to max of 5 letters, and not 3 based on feedback from DAO leads

2️⃣  In the success popup after creating token the tertiary link says "view token page" currently it takes to dashboard, but needs to take to token viewers "https://dev.gleev.xyz/channel/22?tab=Token

3️⃣   From the token preview page there's no way to go back to token editing without 4 extra clicks. 
<img width="582" alt="Screenshot 2024-03-14 at 21 09 42" src="https://github.com/Joystream/atlas/assets/93924525/c42351f8-2e4e-48a4-95dc-e579ff168464">

Suggestion add this button to the channel view token tab for channel owners:
<img width="263" alt="Screenshot 2024-03-14 at 21 10 01" src="https://github.com/Joystream/atlas/assets/93924525/36358ffa-0137-46b8-b6e2-d4979753c990">


4️⃣    The section with Token title looks different from designs,

- grey background
- extra space which is idle
- total supply moved to top but bottom element needs more spacing now

Implementation
<img width="278" alt="Screenshot 2024-03-14 at 21 11 58" src="https://github.com/Joystream/atlas/assets/93924525/4b9b2a32-b643-4c7c-9a0d-832f79ae6689">

Design
<img width="381" alt="Screenshot 2024-03-14 at 21 12 11" src="https://github.com/Joystream/atlas/assets/93924525/2abef190-ab21-4d74-ae9f-2a85e05b7d87">

5️⃣   Add benefit button has different design in Figma

<img width="566" alt="Screenshot 2024-03-14 at 21 13 12" src="https://github.com/Joystream/atlas/assets/93924525/566dd72f-ad0d-475d-b45e-2bd2ca3e21f0">
<img width="678" alt="Screenshot 2024-03-14 at 21 12 46" src="https://github.com/Joystream/atlas/assets/93924525/dd5920ee-b71e-4296-a157-8f35a4ae9b65">

6️⃣ 

We have settings on marketplace page that are not yet implemented, which I suggest to hide

HIde "On Sale" option
<img width="274" alt="Screenshot 2024-03-14 at 21 46 32" src="https://github.com/Joystream/atlas/assets/93924525/c8dc8f1f-69a9-46b8-aa01-8ff98f8f4cda">

Hide whitelist filter
<img width="202" alt="Screenshot 2024-03-14 at 21 46 22" 
src="https://github.com/Joystream/atlas/assets/93924525/36a1d7d1-e4ae-4db2-9b14-76b03dc5c758">

**Comment by dmtrjsg** [comment]
### Tokens Minting

1️⃣   Input field pre-set for Initial tokens minting should be 10,000

Also suggest to introduce limits on the input:
- Lower bound on tokens should be 10k
- Upper bound should be 1bn


### AMM


1️⃣  Update price per unit to `Price for first unit`. 
Add tooltip text `Price of each next token purchased goes up. This is based on the initially minted token supply and new tokens minted. The lesser tokens are available in supply, the higher the price increase for each token purchased." 

Also suggesting to add Add `Average price per unit` to the purchase modal which will indicate how much actually person pays 

<img width="687" alt="Screenshot 2024-03-14 at 22 08 17" src="https://github.com/Joystream/atlas/assets/93924525/84b065c9-c159-41b1-bee2-4add426d4c32">

<img width="760" alt="Screenshot 2024-03-14 at 22 08 01" src="https://github.com/Joystream/atlas/assets/93924525/1affb22a-a7a5-4cf8-b78b-22f88326fe66">

2️⃣  For some reason I have minted 10 tokens set up revenue share at 50% and have only `6 transferable tokens`  in the dashboard


3️⃣   Starting market UI alignment issue

<img width="1034" alt="Screenshot 2024-03-14 at 22 02 44" src="https://github.com/Joystream/atlas/assets/93924525/bcce6b7c-f378-4b18-ac44-a62479edba75">

<img width="767" alt="Screenshot 2024-03-14 at 22 03 24" src="https://github.com/Joystream/atlas/assets/93924525/d981534e-09c8-4030-8913-86a5e978ec99">

**Comment by dmtrjsg** [comment]
Minting Flow
1. CRT title: Lower case -> Upper case automatically
2. Default supply: 1bn (he tried upper limit), tried to do 100bn. 
3. Assurances: Custom - would be good if they could write that and not select from drop down
4. Upper limit: allows input but gives validation error. Now set at 100k
5. Annual reward: was not clear, what annual creator rewards were
6. Final screen: ratio is incorrect for Revenue share ratio - flips holders and creators 
7. Max inflation selection - also fails to the point of preventing TX
Confirmation (View your token page) - have an ability to open up in a new window

Dashboard
Looks amazing!
Loved the onboarding
1. Arrows for progress are useless
2. Tooltip for Token master is required. Or not make it clickable
3. Right click does not offer option in the new page
4. For multiple channels CRT dash resets to the first channel 
5. Brandon had a question - who sets the price for CRT in $. 

Editing token page
1. Video uploaded did not pick up for setting up as CRT trailer from the first go
2. Loves the dashboard for holders on the tokens preview list
3. Holders view in editing does not have actions or filters. Would be cool to have
4. After description added the stage was still token master

Starting AMM
1. Had a bug
2. Market Started Pop up, wording is unclear in all options. 

For new channel
1. Empty channel placeholder screen should invite users to create token and point to studio

View channel token
- At 50% vesting, on the token it still said 10k vested.

Starting revenue share
1. Available revenue share has no CTA. 
2. You need to Design Revenue share in a way that includes. 
3. He would not know what close market does (its red and its unclear if its bad to close?) - @msmadeline let's make it not red. 
4. Wording on Start revenue share modal is unclear. “All tokens will be shared” - needs rewording. When the balance is Zero display this in the Revenue share modal so user does not have an error.  @msmadeline  let's display a warning that revenue split can only be started when channel rewards balance is positive. 

Buying tokens on AMM

1. Slippage tolerance was allowed to be exceeded in the interfaces. 

Suggestions
1. Token master needs to be achieved without revenue split @msmadeline  can you pls address this point?
