### ISSUE TITLE
Design proper video tiles display

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#928]
There is a longliving issue about the way we display video tiles and how we scale them in a grid. This has to be done to tackle responsiveness of screens with video tiles on them.

# Todo
- [x] Explore different approaches to video tiles scaling
- [x] Rework video tile component
- [x] Prepare a scalable prototype of the new scaling approach
- [x] Prepare final RWD for video content screens

**Comment by KubaMikolajczyk** [comment]
This can be seen here:
Figma: [Figma link](https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=10286%3A263903)
Prototype: [Prototype link](https://www.figma.com/proto/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?page-id=3978%3A4436&node-id=10158%3A266216&viewport=-1457%2C1527%2C0.2441876381635666&scaling=min-zoom)

**Comment by KubaMikolajczyk** [comment]
### 🎥   The video update where I talk about this is here 👇 
[Video tiles + Title area + Channel](https://play.joystream.org/video/2600)
